import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle47Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/Generated800Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle54Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/Generated740Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedCIRCLE1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/Generated810Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/Generated650Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedMONTHWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle56Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedDownload42Widget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle43Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedDownload510Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/Generated670Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle46Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle44Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle53Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle45Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle55Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedSEPTWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedAUGWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedGroup77Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle42Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedEllipse20Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedELECTRICITYBILLSWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/Generated700Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedVerified3Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedBILLAMOUNTWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedJULYWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedRectangle55Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedTARGETWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedSCANANDRECORDYOURMONTHLYBILLWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedJUNEWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedSCAN1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/Generated750Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedVerified1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid20widget/generated/GeneratedCIRCLE2Widget.dart';

/* Frame Android - 20
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid20Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 836.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 232, 243, 235),
                      ),
                    ),
                    Positioned(
                      left: 13.0,
                      top: 13.0,
                      right: null,
                      bottom: null,
                      width: 34.0,
                      height: 40.0,
                      child: GeneratedDownload42Widget4(),
                    ),
                    Positioned(
                      left: 302.0,
                      top: 16.0,
                      right: null,
                      bottom: null,
                      width: 32.0,
                      height: 34.0,
                      child: GeneratedDownload510Widget3(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 328.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 60.0,
                      child: GeneratedRectangle51Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 248.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 60.0,
                      child: GeneratedRectangle52Widget(),
                    ),
                    Positioned(
                      left: 1.0,
                      top: 410.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 60.0,
                      child: GeneratedRectangle53Widget(),
                    ),
                    Positioned(
                      left: 89.0,
                      top: 256.0,
                      right: null,
                      bottom: null,
                      width: 89.0,
                      height: 44.0,
                      child: GeneratedRectangle42Widget3(),
                    ),
                    Positioned(
                      left: 208.0,
                      top: 335.0,
                      right: null,
                      bottom: null,
                      width: 89.0,
                      height: 45.0,
                      child: GeneratedRectangle43Widget3(),
                    ),
                    Positioned(
                      left: 208.0,
                      top: 418.0,
                      right: null,
                      bottom: null,
                      width: 89.0,
                      height: 44.0,
                      child: GeneratedRectangle47Widget2(),
                    ),
                    Positioned(
                      left: 87.0,
                      top: 418.0,
                      right: null,
                      bottom: null,
                      width: 89.0,
                      height: 44.0,
                      child: GeneratedRectangle44Widget2(),
                    ),
                    Positioned(
                      left: 88.0,
                      top: 336.0,
                      right: null,
                      bottom: null,
                      width: 89.0,
                      height: 44.0,
                      child: GeneratedRectangle45Widget3(),
                    ),
                    Positioned(
                      left: 210.0,
                      top: 256.0,
                      right: null,
                      bottom: null,
                      width: 89.0,
                      height: 44.0,
                      child: GeneratedRectangle46Widget3(),
                    ),
                    Positioned(
                      left: 88.0,
                      top: 137.0,
                      right: null,
                      bottom: null,
                      width: 123.0,
                      height: 25.0,
                      child: GeneratedFrame1Widget(),
                    ),
                    Positioned(
                      left: 101.0,
                      top: 115.0,
                      right: null,
                      bottom: null,
                      width: 98.0,
                      height: 45.0,
                      child: GeneratedBILLAMOUNTWidget(),
                    ),
                    Positioned(
                      left: 214.0,
                      top: 135.0,
                      right: null,
                      bottom: null,
                      width: 103.0,
                      height: 35.0,
                      child: GeneratedTARGETWidget(),
                    ),
                    Positioned(
                      left: 7.0,
                      top: 137.0,
                      right: null,
                      bottom: null,
                      width: 103.0,
                      height: 35.0,
                      child: GeneratedMONTHWidget(),
                    ),
                    Positioned(
                      left: 114.0,
                      top: 430.0,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 27.0,
                      child: Generated810Widget(),
                    ),
                    Positioned(
                      left: 238.0,
                      top: 267.0,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 27.0,
                      child: Generated700Widget(),
                    ),
                    Positioned(
                      left: 116.0,
                      top: 267.0,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 27.0,
                      child: Generated670Widget(),
                    ),
                    Positioned(
                      left: 238.0,
                      top: 347.0,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 27.0,
                      child: Generated750Widget(),
                    ),
                    Positioned(
                      left: 116.0,
                      top: 347.0,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 27.0,
                      child: Generated740Widget(),
                    ),
                    Positioned(
                      left: 237.0,
                      top: 430.0,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 27.0,
                      child: Generated800Widget(),
                    ),
                    Positioned(
                      left: 312.0,
                      top: 341.0,
                      right: null,
                      bottom: null,
                      width: 32.0,
                      height: 33.0,
                      child: GeneratedVerified1Widget(),
                    ),
                    Positioned(
                      left: 312.0,
                      top: 262.0,
                      right: null,
                      bottom: null,
                      width: 32.0,
                      height: 33.0,
                      child: GeneratedVerified3Widget(),
                    ),
                    Positioned(
                      left: 312.0,
                      top: 418.0,
                      right: null,
                      bottom: null,
                      width: 34.0,
                      height: 40.0,
                      child: GeneratedCIRCLE1Widget(),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 267.0,
                      right: null,
                      bottom: null,
                      width: 43.0,
                      height: 27.0,
                      child: GeneratedAUGWidget(),
                    ),
                    Positioned(
                      left: 26.0,
                      top: 429.0,
                      right: null,
                      bottom: null,
                      width: 53.0,
                      height: 27.0,
                      child: GeneratedJUNEWidget(),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 349.0,
                      right: null,
                      bottom: null,
                      width: 48.0,
                      height: 27.0,
                      child: GeneratedJULYWidget(),
                    ),
                    Positioned(
                      left: -4.0,
                      top: 168.0,
                      right: null,
                      bottom: null,
                      width: 360.0,
                      height: 60.0,
                      child: GeneratedRectangle54Widget1(),
                    ),
                    Positioned(
                      left: 204.0,
                      top: 175.0,
                      right: null,
                      bottom: null,
                      width: 89.0,
                      height: 45.0,
                      child: GeneratedRectangle55Widget2(),
                    ),
                    Positioned(
                      left: 88.0,
                      top: 176.0,
                      right: null,
                      bottom: null,
                      width: 89.0,
                      height: 44.0,
                      child: GeneratedRectangle56Widget(),
                    ),
                    Positioned(
                      left: 234.0,
                      top: 187.0,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 27.0,
                      child: Generated650Widget(),
                    ),
                    Positioned(
                      left: 308.0,
                      top: 178.0,
                      right: null,
                      bottom: null,
                      width: 34.0,
                      height: 40.0,
                      child: GeneratedCIRCLE2Widget(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 189.0,
                      right: null,
                      bottom: null,
                      width: 51.0,
                      height: 27.0,
                      child: GeneratedSEPTWidget(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 517.0,
                      right: null,
                      bottom: null,
                      width: 337.0,
                      height: 46.0,
                      child: GeneratedSCANANDRECORDYOURMONTHLYBILLWidget(),
                    ),
                    Positioned(
                      left: 76.0,
                      top: 610.0,
                      right: null,
                      bottom: null,
                      width: 194.0,
                      height: 181.0,
                      child: GeneratedEllipse20Widget(),
                    ),
                    Positioned(
                      left: 114.0,
                      top: 633.0,
                      right: null,
                      bottom: null,
                      width: 117.0,
                      height: 119.0,
                      child: GeneratedSCAN1Widget(),
                    ),
                    Positioned(
                      left: 56.0,
                      top: 67.0,
                      right: null,
                      bottom: null,
                      width: 241.0,
                      height: 43.0,
                      child: GeneratedRectangle55Widget3(),
                    ),
                    Positioned(
                      left: 63.0,
                      top: 73.0,
                      right: null,
                      bottom: null,
                      width: 248.0,
                      height: 32.0,
                      child: GeneratedELECTRICITYBILLSWidget(),
                    )
                  ]),
            ),
            Positioned(
              left: 4.547473508864641e-13,
              top: 572.0,
              right: null,
              bottom: null,
              width: 385.0,
              height: 70.0,
              child: GeneratedGroup77Widget2(),
            )
          ]),
    ));
  }
}
