import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid1widget/generated/GeneratedEllipse7Widget6.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid1widget/generated/GeneratedSketch16314286963171Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid1widget/generated/GeneratedEllipse7Widget5.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid1widget/generated/GeneratedEllipse6Widget6.dart';

/* Frame Android - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedAndroid3Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 232, 243, 235),
                  ),
                ),
                Positioned(
                  left: -18.0,
                  top: 410.0,
                  right: null,
                  bottom: null,
                  width: 196.0764617919922,
                  height: 212.56353759765625,
                  child: GeneratedEllipse7Widget5(),
                ),
                Positioned(
                  left: -63.32000732421875,
                  top: -172.82000732421875,
                  right: null,
                  bottom: null,
                  width: 360.5577392578125,
                  height: 339.653076171875,
                  child: GeneratedEllipse7Widget6(),
                ),
                Positioned(
                  left: 223.0,
                  top: 228.0,
                  right: null,
                  bottom: null,
                  width: 196.68687438964844,
                  height: 205.8211212158203,
                  child: GeneratedEllipse6Widget6(),
                ),
                Positioned(
                  left: 0.0,
                  top: -55.0,
                  right: null,
                  bottom: null,
                  width: 428.0,
                  height: 660.0,
                  child: GeneratedSketch16314286963171Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
