import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedevehiclesWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedTRANSPORTATIONWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/Generated75Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedDownload510Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedGroup77Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/Generated8456652Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedElectricvehicle1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedGroup51Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedGroup50Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/Generated50Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedMoretogo375kmWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedDownload42Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedwalkingWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedMonthlyGoal1500kmWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid19widget/generated/GeneratedRectangle55Widget1.dart';

/* Frame Android - 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid19Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 243, 235),
                ),
              ),
              Positioned(
                left: 13.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 40.0,
                child: GeneratedDownload42Widget3(),
              ),
              Positioned(
                left: 302.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 34.0,
                child: GeneratedDownload510Widget2(),
              ),
              Positioned(
                left: 19.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 181.0,
                child: GeneratedGroup50Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 17.0,
                child: Generated8456652Widget3(),
              ),
              Positioned(
                left: 19.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 181.0,
                child: GeneratedGroup51Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 45.0,
                child: GeneratedElectricvehicle1Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 20.0,
                child: GeneratedMonthlyGoal1500kmWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 16.0,
                child: Generated75Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 20.0,
                child: GeneratedMoretogo375kmWidget(),
              ),
              Positioned(
                left: 295.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 23.0,
                child: Generated50Widget3(),
              ),
              Positioned(
                left: 84.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 38.0,
                child: GeneratedwalkingWidget(),
              ),
              Positioned(
                left: 102.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 38.0,
                child: GeneratedevehiclesWidget(),
              ),
              Positioned(
                left: 62.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 43.0,
                child: GeneratedRectangle55Widget1(),
              ),
              Positioned(
                left: 69.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 35.0,
                child: GeneratedTRANSPORTATIONWidget(),
              ),
              Positioned(
                left: 4.547473508864641e-13,
                top: 572.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 75.0,
                child: GeneratedGroup77Widget1(),
              )
            ]),
      ),
    ));
  }
}
