description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Inter-300.ttf"
          style: "normal"
          weight: 300
    - 
      family: "Quicksand"
      fonts: 
        - 
          asset: "fonts/Quicksand-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Quicksand-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Quicksand-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Quicksand-300.ttf"
          style: "normal"
          weight: 300
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Roboto-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Roboto-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Roboto-300.ttf"
          style: "normal"
          weight: 300
    - 
      family: "Saira"
      fonts: 
        - 
          asset: "fonts/Saira-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Quantico"
      fonts: 
        - 
          asset: "fonts/Quantico-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Sarala"
      fonts: 
        - 
          asset: "fonts/Sarala-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Overpass"
      fonts: 
        - 
          asset: "fonts/Overpass-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
