import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid10widget/generated/GeneratedGroup85Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid10widget/generated/GeneratedEllipse6Widget5.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid10widget/generated/GeneratedInputTextWidget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid10widget/generated/GeneratedInputTextWidget5.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid10widget/generated/GeneratedButtonPrimaryWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid10widget/generated/GeneratedEllipse5Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid10widget/generated/GeneratedEllipse7Widget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid10widget/generated/GeneratedInputTextWidget6.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid10widget/generated/GeneratedLOGINWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Android - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 362.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 243, 235),
                ),
              ),
              Positioned(
                left: 212.4999542236328,
                top: 225.02548217773438,
                right: null,
                bottom: null,
                width: 196.68687438964844,
                height: 205.8211212158203,
                child: GeneratedEllipse6Widget5(),
              ),
              Positioned(
                left: -63.318939208984375,
                top: -172.824462890625,
                right: null,
                bottom: null,
                width: 360.5577392578125,
                height: 339.653076171875,
                child: GeneratedEllipse5Widget1(),
              ),
              Positioned(
                left: 90.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 70.0,
                child: GeneratedLOGINWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 142.0,
                right: 19.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget4(),
              ),
              Positioned(
                left: 19.0,
                top: 224.0,
                right: 19.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget5(),
              ),
              Positioned(
                left: 19.0,
                top: 306.0,
                right: 19.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget6(),
              ),
              Positioned(
                left: -42.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 196.0764617919922,
                height: 212.56353759765625,
                child: GeneratedEllipse7Widget4(),
              ),
              Positioned(
                left: 76.0,
                top: null,
                right: 61.0,
                bottom: 158.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.0856353591160221;

                  final double height = constraints.maxHeight * 0.0625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.03879895921570162,
                        y: constraints.maxHeight * 0.021875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup85Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
