import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedChangeWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedProductDescriptionWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedSpecialpriceWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedShoppingcart2Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle35Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedBuyNowWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedAdd1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle27Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle20Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedGroup81Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedLoupe2Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle28Widget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedAddtocart1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedAOneWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedLike1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedPolygon3Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/Generated96744913stariconwhiteiconwithshadowontransparentbackgro.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRupee21Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedPolygon2Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedAvailablecouponsWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle29Widget7.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedToothbrush_origremovebgpreview2Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle26Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/Generated49Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/Generated20offWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedHeart2Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedBambooToothbrushSetWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/Generated199Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedReviewsandRatingsWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle20Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedDelivertoSaraWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedEllipse13Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid15widget/generated/GeneratedPolygon4Widget.dart';

/* Frame Android - 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 243, 235),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle20Widget2(),
              ),
              Positioned(
                left: 24.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 38.0,
                child: GeneratedLoupe2Widget1(),
              ),
              Positioned(
                left: 324.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 27.0,
                child: GeneratedShoppingcart2Widget(),
              ),
              Positioned(
                left: 293.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 25.0,
                child: GeneratedHeart2Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 244.0,
                child: GeneratedRectangle20Widget3(),
              ),
              Positioned(
                left: 58.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 194.0,
                child: GeneratedToothbrush_origremovebgpreview2Widget(),
              ),
              Positioned(
                left: 126.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 6.0,
                child: GeneratedRectangle21Widget1(),
              ),
              Positioned(
                left: 144.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 9.0,
                child: GeneratedEllipse11Widget(),
              ),
              Positioned(
                left: 157.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 9.0,
                child: GeneratedEllipse12Widget(),
              ),
              Positioned(
                left: 171.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 9.0,
                child: GeneratedEllipse13Widget(),
              ),
              Positioned(
                left: 185.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 9.0,
                child: GeneratedEllipse14Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 30.0,
                child: GeneratedAOneWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 18.0,
                child: GeneratedBambooToothbrushSetWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 14.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 14.0,
                child: GeneratedRectangle27Widget1(),
              ),
              Positioned(
                left: 28.0,
                top: 529.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 14.0,
                child: GeneratedRectangle29Widget7(),
              ),
              Positioned(
                left: 31.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 14.0,
                child: GeneratedRectangle35Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 20.0,
                child: GeneratedDelivertoSaraWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 14.0,
                child: GeneratedRectangle28Widget4(),
              ),
              Positioned(
                left: 28.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 20.0,
                child: GeneratedAvailablecouponsWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 18.0,
                child: GeneratedSpecialpriceWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRupee21Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 32.0,
                child: Generated199Widget1(),
              ),
              Positioned(
                left: 119.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 20.0,
                child: Generated20offWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 18.0,
                child: GeneratedRectangle26Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 20.0,
                child: Generated49Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child:
                    Generated96744913stariconwhiteiconwithshadowontransparentbackgro(),
              ),
              Positioned(
                left: 237.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 45.0,
                child: GeneratedLike1Widget(),
              ),
              Positioned(
                left: 280.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 32.0,
                child: GeneratedAddtocart1Widget(),
              ),
              Positioned(
                left: 247.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 15.0,
                child: GeneratedAdd1Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 7.0,
                child: GeneratedPolygon2Widget1(),
              ),
              Positioned(
                left: 162.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 7.0,
                child: GeneratedPolygon3Widget1(),
              ),
              Positioned(
                left: 173.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 7.0,
                child: GeneratedPolygon4Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 20.0,
                child: GeneratedProductDescriptionWidget(),
              ),
              Positioned(
                left: 151.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 11.0,
                child: GeneratedRectangle31Widget(),
              ),
              Positioned(
                left: 157.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 17.0,
                child: GeneratedChangeWidget(),
              ),
              Positioned(
                left: 205.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 47.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 212.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 31.0,
                child: GeneratedRectangle33Widget(),
              ),
              Positioned(
                left: 228.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 31.0,
                child: GeneratedBuyNowWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 549.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 20.0,
                child: GeneratedReviewsandRatingsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 73.0,
                child: GeneratedGroup81Widget1(),
              )
            ]),
      ),
    ));
  }
}
