import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated8456654Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedYouractionsWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated100Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated50Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle29Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle41Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated100Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedTrackingyourelectricitybillWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedTonsofCO2Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedYourcarbonfootprintWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated673Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated80Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedYourcountryWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedYouWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated8456652Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated864Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedUsereusablebagswhileshoppingWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated98Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle30Widget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedGroup76Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle39Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedSyncwithactionsWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle29Widget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedImage14Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated558Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedDownload42Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedWorldWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated100Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle30Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated8456653Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedSketch16313482564811Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated500Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedDownload43Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedVectorWidget36.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedSwitchtoVegetarianDietWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedActivityWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/Generated90Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedEcofriendlyTransportationWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid7widget/generated/GeneratedRectangle30Widget3.dart';

/* Frame Android - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 657.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 232, 243, 235),
                      ),
                    ),
                    Positioned(
                      left: 301.0,
                      top: 539.0,
                      right: null,
                      bottom: null,
                      width: 46.0,
                      height: 41.0,
                      child: GeneratedDownload43Widget1(),
                    ),
                    Positioned(
                      left: 2.2737367544323206e-13,
                      top: 572.0,
                      right: null,
                      bottom: null,
                      width: 385.0,
                      height: 75.0,
                      child: GeneratedGroup76Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.5222222222222223;

                        final double height =
                            constraints.maxHeight * 0.026429476803296232;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.1361111111111111,
                              y: constraints.maxHeight * 0.5515253772474316,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedTrackingyourelectricitybillWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.06944444444444445;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 25.0;

                        double percentHeight = 0.0390625;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                25.6640625;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.8777777777777778,
                              translateY:
                                  constraints.maxHeight * 0.025000010451225387,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget36())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 61.0,
                      top: 11.0,
                      right: null,
                      bottom: null,
                      width: 113.0,
                      height: 43.0,
                      child: GeneratedActivityWidget(),
                    ),
                    Positioned(
                      left: 43.0,
                      top: 328.0,
                      right: null,
                      bottom: null,
                      width: 110.0,
                      height: 25.0,
                      child: GeneratedYouractionsWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.12222222222222222;

                        final double height =
                            constraints.maxHeight * 0.023200535883097888;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.4166666666666667,
                              y: constraints.maxHeight * 0.24427899922410104,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: Generated558Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth * 0.175;

                        final double height =
                            constraints.maxHeight * 0.023200535883097888;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.55,
                              y: constraints.maxHeight * 0.2167427841023949,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: Generated673Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.17222222222222222;

                        final double height =
                            constraints.maxHeight * 0.022086922980878994;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.26944444444444443,
                              y: constraints.maxHeight * 0.4459665144596651,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedYouWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.2419713338216146;

                        final double height =
                            constraints.maxHeight * 0.030292249705693493;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.39444444444444443,
                              y: constraints.maxHeight * 0.4459665144596651,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedYourcountryWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.1527777777777778;

                        final double height =
                            constraints.maxHeight * 0.023200559108043188;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.5555555555555556,
                              y: constraints.maxHeight * 0.4459665144596651,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedWorldWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.2514631059434679;

                        final double height =
                            constraints.maxHeight * 0.0243531202435312;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.14166666666666666,
                              y: constraints.maxHeight * 0.3703272106803534,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedTonsofCO2Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.15833333333333333;

                        final double height =
                            constraints.maxHeight * 0.017520747772634845;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.26944444444444443,
                              y: constraints.maxHeight * 0.18485871987074295,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: Generated864Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.4388888888888889;

                        final double height =
                            constraints.maxHeight * 0.01974798518954528;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.14722222222222223,
                              y: constraints.maxHeight * 0.7899543378995434,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    GeneratedEcofriendlyTransportationWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.532387203640408;

                        final double height =
                            constraints.maxHeight * 0.0106544901065449;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.16111111111111112,
                              y: constraints.maxHeight * 0.8234398782343988,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedRectangle29Widget3(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.35833333333333334;

                        final double height =
                            constraints.maxHeight * 0.0106544901065449;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.1361111111111111,
                              y: constraints.maxHeight * 0.8234398782343988,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedRectangle30Widget2(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.062057240804036455;

                        final double height =
                            constraints.maxHeight * 0.01763265717156583;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.08611111111111111,
                              y: constraints.maxHeight * 0.8203957382039574,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: Generated80Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.07777777777777778;

                        final double height =
                            constraints.maxHeight * 0.025001653616105405;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.7916666666666666,
                              y: constraints.maxHeight * 0.5558732263573772,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: Generated100Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.10555555555555556;

                        final double height =
                            constraints.maxHeight * 0.02934954917594178;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.7916666666666666,
                              y: constraints.maxHeight * 0.7945205479452054,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: Generated100Widget1(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 7.0,
                      top: 11.0,
                      right: null,
                      bottom: null,
                      width: 34.0,
                      height: 40.0,
                      child: GeneratedDownload42Widget2(),
                    ),
                    Positioned(
                      left: 220.0,
                      top: 90.0,
                      right: null,
                      bottom: null,
                      width: 136.0,
                      height: 25.0,
                      child: GeneratedRectangle32Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.5833333333333334;

                        final double height =
                            constraints.maxHeight * 0.0319634703196347;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.11666666666666667,
                              y: constraints.maxHeight * 0.1050228310502283,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedYourcarbonfootprintWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.041666666666666664;

                        final double height =
                            constraints.maxHeight * 0.01875000928997812;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.6305555555555555,
                              y: constraints.maxHeight * 0.1461187214611872,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedImage14Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.2916666666666667;

                        final double height =
                            constraints.maxHeight * 0.02804414467543046;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.6777777777777778,
                              y: constraints.maxHeight * 0.1400304414003044,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedSyncwithactionsWidget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.06205725140041775;

                        final double height =
                            constraints.maxHeight * 0.021672868656059743;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.08611111111111111,
                              y: constraints.maxHeight * 0.5761630495207858,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: Generated98Widget(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 23.0,
                      top: 464.0,
                      right: null,
                      bottom: null,
                      width: 296.0,
                      height: 43.0,
                      child: GeneratedRectangle40Widget(),
                    ),
                    Positioned(
                      left: 28.0,
                      top: 355.0,
                      right: null,
                      bottom: null,
                      width: 296.0,
                      height: 43.0,
                      child: GeneratedRectangle42Widget(),
                    ),
                    Positioned(
                      left: 39.0,
                      top: 469.0,
                      right: null,
                      bottom: null,
                      width: 158.0,
                      height: 18.0,
                      child: GeneratedSwitchtoVegetarianDietWidget(),
                    ),
                    Positioned(
                      left: 28.0,
                      top: 407.0,
                      right: null,
                      bottom: null,
                      width: 296.0,
                      height: 43.0,
                      child: GeneratedRectangle39Widget1(),
                    ),
                    Positioned(
                      left: 45.0,
                      top: 415.0,
                      right: null,
                      bottom: null,
                      width: 210.0,
                      height: 18.0,
                      child: GeneratedUsereusablebagswhileshoppingWidget(),
                    ),
                    Positioned(
                      left: 260.0,
                      top: 423.0,
                      right: null,
                      bottom: null,
                      width: 20.0,
                      height: 17.0,
                      child: Generated8456652Widget2(),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 515.0,
                      right: null,
                      bottom: null,
                      width: 296.0,
                      height: 43.0,
                      child: GeneratedRectangle41Widget3(),
                    ),
                    Positioned(
                      left: 256.0,
                      top: 469.0,
                      right: null,
                      bottom: null,
                      width: 20.0,
                      height: 17.0,
                      child: Generated8456653Widget2(),
                    ),
                    Positioned(
                      left: 256.0,
                      top: 519.0,
                      right: null,
                      bottom: null,
                      width: 20.0,
                      height: 17.0,
                      child: Generated8456654Widget1(),
                    ),
                    Positioned(
                      left: 291.0,
                      top: 412.0,
                      right: null,
                      bottom: null,
                      width: 21.0,
                      height: 21.0,
                      child: Generated50Widget2(),
                    ),
                    Positioned(
                      left: 286.0,
                      top: 458.0,
                      right: null,
                      bottom: null,
                      width: 29.0,
                      height: 21.0,
                      child: Generated500Widget2(),
                    ),
                    Positioned(
                      left: 52.0,
                      top: 491.0,
                      right: null,
                      bottom: null,
                      width: 191.65939331054688,
                      height: 7.0,
                      child: GeneratedRectangle29Widget4(),
                    ),
                    Positioned(
                      left: 52.0,
                      top: 491.0,
                      right: null,
                      bottom: null,
                      width: 172.0,
                      height: 7.0,
                      child: GeneratedRectangle30Widget3(),
                    ),
                    Positioned(
                      left: 47.0,
                      top: 435.0,
                      right: null,
                      bottom: null,
                      width: 195.0,
                      height: 7.0,
                      child: GeneratedRectangle43Widget(),
                    ),
                    Positioned(
                      left: 28.0,
                      top: 491.0,
                      right: null,
                      bottom: null,
                      width: 22.34061050415039,
                      height: 14.0,
                      child: Generated90Widget(),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 426.0,
                      right: null,
                      bottom: null,
                      width: 37.0,
                      height: 15.0,
                      child: Generated100Widget2(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.5217411041259765;

                        final double height =
                            constraints.maxHeight * 0.010937602189759322;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.1361111111111111,
                              y: constraints.maxHeight * 0.5834094182541382,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedRectangle30Widget4(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 42.0,
              top: 11.0,
              right: null,
              bottom: null,
              width: 272.0,
              height: 378.0,
              child: GeneratedSketch16313482564811Widget(),
            )
          ]),
    ));
  }
}
