import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedDashboardWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedThrissurKeralaWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedImage12Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedFrameWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedLevel1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/Generated8456651Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedTipofthedayWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedVectorWidget5.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedVectorWidget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedYouractionsandgoalsWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedWelcomeSaraWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedImage10Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedDiscoverwaystoimproveyourlifeWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedWhatsyoursteptowardssustainabilitytodayWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedChallengeafriendWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedGroup75Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedImage11Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/Generated12Sep2021Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/Generated177Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedUsecoinsWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedImage9Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedMedal1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedFF1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedTurnoffelectronicdeviceswhenyouaremovingoutforacoupleof.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid4widget/generated/GeneratedRectangle41Widget1.dart';

/* Frame Android - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 657.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 243, 235),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06666666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 24.0;

                  double percentHeight = 0.03750001857995624;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      24.63751220703125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.13333333333333333,
                        translateY: constraints.maxHeight * 0.890625,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget4())
                  ]);
                }),
              ),
              Positioned(
                left: 52.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 43.0,
                child: GeneratedDashboardWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0380517503805175;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8666666666666667,
                        translateY: constraints.maxHeight * 0.0167427701674277,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget5())
                  ]);
                }),
              ),
              Positioned(
                left: 21.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 33.0,
                child: GeneratedWelcomeSaraWidget(),
              ),
              Positioned(
                left: 200.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 157.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 162.0,
                child:
                    GeneratedTurnoffelectronicdeviceswhenyouaremovingoutforacoupleof(),
              ),
              Positioned(
                left: 211.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 23.0,
                child: GeneratedTipofthedayWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 23.0,
                child: GeneratedChallengeafriendWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 33.0,
                child: GeneratedYouractionsandgoalsWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 52.0,
                child: GeneratedWhatsyoursteptowardssustainabilitytodayWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 17.0,
                child: GeneratedRectangle16Widget1(),
              ),
              Positioned(
                left: 64.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 17.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 104.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 24.0,
                child: Generated177Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 17.0,
                child: Generated8456651Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 23.0,
                child: GeneratedFrameWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 44.0,
                child: GeneratedDiscoverwaystoimproveyourlifeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 76.0,
                child: GeneratedGroup75Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 103.0,
                child: GeneratedFF1Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 16.0,
                child: GeneratedMedal1Widget(),
              ),
              Positioned(
                left: 92.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 15.0,
                child: GeneratedLevel1Widget(),
              ),
              Positioned(
                left: 256.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 23.0,
                child: GeneratedImage9Widget(),
              ),
              Positioned(
                left: 238.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 21.0,
                child: GeneratedThrissurKeralaWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 31.0,
                child: GeneratedImage10Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 31.0,
                child: GeneratedImage11Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 31.0,
                child: GeneratedImage12Widget(),
              ),
              Positioned(
                left: 238.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 21.0,
                child: Generated12Sep2021Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 43.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 43.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 43.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 23.0,
                child: GeneratedRectangle41Widget1(),
              ),
              Positioned(
                left: 79.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 20.0,
                child: GeneratedUsecoinsWidget(),
              )
            ]),
      ),
    ));
  }
}
