import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedRectangle67Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/Generated500Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedGroup71Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedExcludeWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedHighimpactactionsWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedRectangle55Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/Generated500Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedGroup53Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedModerateimpactactionsWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedImage21Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedRectangle69Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/Generated8456658Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedGroup69Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedECOTIPSWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedImage19Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedExcludeWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedGroup73Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedDownload44Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedSwitchtogreenenergyWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedGroup70Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid2widget/generated/GeneratedLowimpactactionsWidget.dart';

/* Frame Android - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1083.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 357.0,
                            height: 1083.0,
                            decoration: BoxDecoration(
                              border: Border.all(
                                width: 1.0,
                                color: Color.fromARGB(255, 0, 0, 0),
                              ),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 232, 243, 235),
                                    ),
                                  ),
                                  Positioned(
                                    left: 62.0,
                                    top: 53.0,
                                    right: null,
                                    bottom: null,
                                    width: 241.0,
                                    height: 43.0,
                                    child: GeneratedRectangle55Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.07225434118960083;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          25.7947998046875;

                                      double percentHeight =
                                          0.020210186860567976;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          21.887632369995117;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.8851540616246498,
                                            translateY: constraints.maxHeight *
                                                0.015359741168669385,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedVectorWidget())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 12.0,
                                    top: 11.0,
                                    right: null,
                                    bottom: null,
                                    width: 34.0,
                                    height: 40.0,
                                    child: GeneratedDownload44Widget(),
                                  ),
                                  Positioned(
                                    left: 115.0,
                                    top: 63.0,
                                    right: null,
                                    bottom: null,
                                    width: 265.0,
                                    height: 39.0,
                                    child: GeneratedECOTIPSWidget(),
                                  ),
                                  Positioned(
                                    left: 19.0,
                                    top: 117.0,
                                    right: null,
                                    bottom: null,
                                    width: 233.0,
                                    height: 31.0,
                                    child: GeneratedHighimpactactionsWidget(),
                                  ),
                                  Positioned(
                                    left: 22.0,
                                    top: 439.0,
                                    right: null,
                                    bottom: null,
                                    width: 291.0,
                                    height: 31.0,
                                    child:
                                        GeneratedModerateimpactactionsWidget(),
                                  ),
                                  Positioned(
                                    left: 23.0,
                                    top: 777.0,
                                    right: null,
                                    bottom: null,
                                    width: 227.0,
                                    height: 31.0,
                                    child: GeneratedLowimpactactionsWidget(),
                                  ),
                                  Positioned(
                                    left: 19.0,
                                    top: 158.0,
                                    right: null,
                                    bottom: null,
                                    width: 321.0,
                                    height: 212.0,
                                    child: GeneratedRectangle67Widget(),
                                  ),
                                  Positioned(
                                    left: 126.0,
                                    top: 392.0,
                                    right: null,
                                    bottom: null,
                                    width: 117.0,
                                    height: 16.0,
                                    child: GeneratedGroup69Widget(),
                                  ),
                                  Positioned(
                                    left: 121.0,
                                    top: 724.0,
                                    right: null,
                                    bottom: null,
                                    width: 117.0,
                                    height: 16.0,
                                    child: GeneratedExcludeWidget(),
                                  ),
                                  Positioned(
                                    left: 121.0,
                                    top: 1054.0,
                                    right: null,
                                    bottom: null,
                                    width: 117.0,
                                    height: 16.0,
                                    child: GeneratedExcludeWidget1(),
                                  ),
                                  Positioned(
                                    left: 108.0,
                                    top: 844.0,
                                    right: null,
                                    bottom: null,
                                    width: 117.0,
                                    height: 15.0,
                                    child: GeneratedGroup70Widget(),
                                  ),
                                  Positioned(
                                    left: 19.0,
                                    top: 157.0,
                                    right: null,
                                    bottom: null,
                                    width: 321.0,
                                    height: 138.0,
                                    child: GeneratedImage19Widget(),
                                  ),
                                  Positioned(
                                    left: 46.0,
                                    top: 295.0,
                                    right: null,
                                    bottom: null,
                                    width: 221.0,
                                    height: 27.0,
                                    child: GeneratedSwitchtogreenenergyWidget(),
                                  ),
                                  Positioned(
                                    left: 37.0,
                                    top: 324.0,
                                    right: null,
                                    bottom: null,
                                    width: 30.0,
                                    height: 32.0,
                                    child: Generated8456658Widget(),
                                  ),
                                  Positioned(
                                    left: 75.0,
                                    top: 331.0,
                                    right: null,
                                    bottom: null,
                                    width: 41.0,
                                    height: 30.0,
                                    child: Generated500Widget(),
                                  ),
                                  Positioned(
                                    left: 73.0,
                                    top: 667.0,
                                    right: null,
                                    bottom: null,
                                    width: 41.0,
                                    height: 30.0,
                                    child: Generated500Widget1(),
                                  ),
                                  Positioned(
                                    left: 158.0,
                                    top: 331.0,
                                    right: null,
                                    bottom: null,
                                    width: 153.0,
                                    height: 25.0,
                                    child: GeneratedGroup71Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 808.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 229.0,
                                    child: GeneratedRectangle69Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 481.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 546.0,
                                    child: GeneratedGroup73Widget(),
                                  ),
                                  Positioned(
                                    left: 19.0,
                                    top: 806.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 162.0,
                                    child: GeneratedImage21Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 9.094947017729282e-13,
              top: 572.0,
              right: null,
              bottom: null,
              width: 359.0,
              height: 70.43412780761719,
              child: GeneratedGroup53Widget(),
            )
          ]),
    ));
  }
}
