import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedGroup81Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedWhatsAppImage20210911at11483Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedWhatsAppImage20210911at11482Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedDownload42Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedPolygon3Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedDownload22Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedWhatsAppImage20210911at11485Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedNEWSWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedWhatsAppImage20210911at11484Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedRectangle71Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid14widget/generated/GeneratedDownload52Widget.dart';

/* Frame Android - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid14Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1487.268798828125,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 346.0,
                            height: 1487.0,
                            decoration: BoxDecoration(
                              border: Border.all(
                                width: 1.0,
                                color: Color.fromARGB(255, 0, 0, 0),
                              ),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 232, 243, 235),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 631.0,
                                    right: null,
                                    bottom: null,
                                    width: 346.0,
                                    height: 102.0,
                                    child:
                                        GeneratedWhatsAppImage20210911at11483Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 733.0,
                                    right: null,
                                    bottom: null,
                                    width: 346.0,
                                    height: 158.90370178222656,
                                    child:
                                        GeneratedWhatsAppImage20210911at11484Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 65.0,
                                    right: null,
                                    bottom: null,
                                    width: 346.0,
                                    height: 566.3427124023438,
                                    child:
                                        GeneratedWhatsAppImage20210911at11482Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 892.0,
                                    right: null,
                                    bottom: null,
                                    width: 346.0,
                                    height: 595.268798828125,
                                    child:
                                        GeneratedWhatsAppImage20210911at11485Widget(),
                                  ),
                                  Positioned(
                                    left: 11.0,
                                    top: 10.0,
                                    right: null,
                                    bottom: null,
                                    width: 34.0,
                                    height: 40.0,
                                    child: GeneratedDownload42Widget1(),
                                  ),
                                  Positioned(
                                    left: 45.0,
                                    top: 10.0,
                                    right: null,
                                    bottom: null,
                                    width: 241.0,
                                    height: 43.0,
                                    child: GeneratedRectangle16Widget(),
                                  ),
                                  Positioned(
                                    left: 105.0,
                                    top: 17.0,
                                    right: null,
                                    bottom: null,
                                    width: 97.0,
                                    height: 35.0,
                                    child: GeneratedNEWSWidget(),
                                  ),
                                  Positioned(
                                    left: 60.7978515625,
                                    top: 15.0,
                                    right: null,
                                    bottom: null,
                                    width: 32.351219177246094,
                                    height: 33.55601501464844,
                                    child: GeneratedDownload22Widget(),
                                  ),
                                  Positioned(
                                    left: 298.0,
                                    top: 14.0,
                                    right: null,
                                    bottom: null,
                                    width: 38.0,
                                    height: 34.0,
                                    child: GeneratedDownload52Widget(),
                                  ),
                                  Positioned(
                                    left: 287.0,
                                    top: 427.0,
                                    right: null,
                                    bottom: null,
                                    width: 9.0,
                                    height: 7.0,
                                    child: GeneratedPolygon3Widget(),
                                  ),
                                  Positioned(
                                    left: 194.0,
                                    top: 54.0,
                                    right: null,
                                    bottom: null,
                                    width: 100.0,
                                    height: 100.0,
                                    child: GeneratedRectangle71Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 9.094947017729282e-13,
              top: 572.0,
              right: null,
              bottom: null,
              width: 385.0,
              height: 76.0,
              child: GeneratedGroup81Widget(),
            )
          ]),
    ));
  }
}
