import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedGroup79Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedVIEWMOREWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedVectorWidget20.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedVectorWidget21.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedEXPLOREWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedPolygon2Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedStreetDogCareAssistantKolkataINDIAWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedDownload12Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedDownload32Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedDownload11Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedVOLUNTEERINGWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedDownload41Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedGroup82Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedFiltersWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedGroup83Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedDETAILSWidget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedVectorWidget19.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid12widget/generated/GeneratedDownload3Widget.dart';

/* Frame Android - 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 797.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 232, 243, 235),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.06666666666666667;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 24.0;

                        double percentHeight = 0.037500015316224905;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                29.88751220703125;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX: constraints.maxWidth * 0.125,
                              translateY:
                                  constraints.maxHeight * 0.8745294855708908,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget19())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 493.0,
                      right: null,
                      bottom: null,
                      width: 303.0,
                      height: 161.0,
                      child: GeneratedGroup83Widget(),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 337.0,
                      right: null,
                      bottom: null,
                      width: 309.0,
                      height: 136.0,
                      child: GeneratedGroup82Widget(),
                    ),
                    Positioned(
                      left: 26.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 306.0,
                      height: 136.0,
                      child: GeneratedRectangle6Widget1(),
                    ),
                    Positioned(
                      left: 60.0,
                      top: 68.0,
                      right: null,
                      bottom: null,
                      width: 241.0,
                      height: 43.0,
                      child: GeneratedRectangle8Widget1(),
                    ),
                    Positioned(
                      left: 72.0,
                      top: 69.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 35.0,
                      child: GeneratedDownload11Widget1(),
                    ),
                    Positioned(
                      left: 23.0,
                      top: 19.0,
                      right: null,
                      bottom: null,
                      width: 34.0,
                      height: 40.0,
                      child: GeneratedDownload41Widget1(),
                    ),
                    Positioned(
                      left: 102.0,
                      top: 74.0,
                      right: null,
                      bottom: null,
                      width: 196.0,
                      height: 32.0,
                      child: GeneratedVOLUNTEERINGWidget1(),
                    ),
                    Positioned(
                      left: 212.0,
                      top: 260.0,
                      right: null,
                      bottom: null,
                      width: 101.0,
                      height: 25.0,
                      child: GeneratedRectangle25Widget(),
                    ),
                    Positioned(
                      left: 236.0,
                      top: 263.0,
                      right: null,
                      bottom: null,
                      width: 73.0,
                      height: 31.0,
                      child: GeneratedDETAILSWidget2(),
                    ),
                    Positioned(
                      left: 60.0,
                      top: 267.0,
                      right: null,
                      bottom: null,
                      width: 27.0,
                      height: 22.0,
                      child: GeneratedDownload3Widget(),
                    ),
                    Positioned(
                      left: 106.0,
                      top: 256.0,
                      right: null,
                      bottom: null,
                      width: 38.0,
                      height: 32.0,
                      child: GeneratedDownload12Widget(),
                    ),
                    Positioned(
                      left: 163.0,
                      top: 260.0,
                      right: null,
                      bottom: null,
                      width: 28.0,
                      height: 29.0,
                      child: GeneratedDownload32Widget(),
                    ),
                    Positioned(
                      left: 45.0,
                      top: 180.0,
                      right: null,
                      bottom: null,
                      width: 270.0,
                      height: 82.0,
                      child:
                          GeneratedStreetDogCareAssistantKolkataINDIAWidget(),
                    ),
                    Positioned(
                      left: 149.0,
                      top: 689.0,
                      right: null,
                      bottom: null,
                      width: 69.0,
                      height: 17.0,
                      child: GeneratedVIEWMOREWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.06666666666666667;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 24.0;

                        double percentHeight = 0.029411746686794228;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                23.441162109375;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.13055555555555556,
                              translateY:
                                  constraints.maxHeight * 0.8932181900388174,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget20())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.06944444444444445;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 25.0;

                        double percentHeight = 0.030637255277358454;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                24.417892456054688;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.8611111111111112,
                              translateY:
                                  constraints.maxHeight * 0.023284313819339614,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget21())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 111.0,
                      top: 21.0,
                      right: null,
                      bottom: null,
                      width: 137.0,
                      height: 43.0,
                      child: GeneratedEXPLOREWidget1(),
                    ),
                    Positioned(
                      left: 26.0,
                      top: 134.0,
                      right: null,
                      bottom: null,
                      width: 64.0,
                      height: 16.0,
                      child: GeneratedRectangle20Widget(),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 135.0,
                      right: null,
                      bottom: null,
                      width: 53.0,
                      height: 20.0,
                      child: GeneratedFiltersWidget1(),
                    ),
                    Positioned(
                      left: 74.0,
                      top: 146.0,
                      right: null,
                      bottom: null,
                      width: 9.0,
                      height: 7.0,
                      child: GeneratedPolygon2Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 9.094947017729282e-13,
              top: 572.0,
              right: null,
              bottom: null,
              width: 385.0,
              height: 75.0,
              child: GeneratedGroup79Widget1(),
            )
          ]),
    ));
  }
}
