import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedShoppingcart1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedToothbrush_origremovebgpreview1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedBiogarbageBagsCompostableM192115pcsWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedPolygon1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedRectangle17Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/Generated199Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedRupeeSymbolWhitePNG3Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedFiltersWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedRupeeSymbolWhitePNG4Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedVectorWidget14.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedRupeeSymbolWhitePNG1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedRupeeSymbolWhitePNG2Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedHeart1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/Generated299Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedOrganicBambootoothbrushSetof4sizeMAone199Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedGroup80Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedSuggestedbasedonyourinterestWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedLoupe1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedGardenWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid8widget/generated/GeneratedViewmoreWidget.dart';

/* Frame Android - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 243, 235),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06666666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 24.0;

                  double percentHeight = 0.0375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 24.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.13333333333333333,
                        translateY: constraints.maxHeight * 0.890625,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget14())
                  ]);
                }),
              ),
              Positioned(
                left: 18.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 136.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 164.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 119.0,
                child:
                    GeneratedOrganicBambootoothbrushSetof4sizeMAone199Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 41.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 37.0,
                child: GeneratedLoupe1Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 97.0,
                child: GeneratedToothbrush_origremovebgpreview1Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 281.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 68.0,
                child: GeneratedBiogarbageBagsCompostableM192115pcsWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 34.0,
                child: GeneratedGardenWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 20.0,
                child: GeneratedRectangle17Widget2(),
              ),
              Positioned(
                left: 18.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 17.0,
                child: GeneratedSuggestedbasedonyourinterestWidget(),
              ),
              Positioned(
                left: 325.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 27.0,
                child: GeneratedShoppingcart1Widget(),
              ),
              Positioned(
                left: 294.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 25.0,
                child: GeneratedHeart1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 16.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 20.0,
                child: GeneratedFiltersWidget(),
              ),
              Positioned(
                left: 72.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 7.0,
                child: GeneratedPolygon1Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 13.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 17.0,
                child: GeneratedViewmoreWidget(),
              ),
              Positioned(
                left: 261.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 21.0,
                child: GeneratedRupeeSymbolWhitePNG1Widget(),
              ),
              Positioned(
                left: 268.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 21.0,
                child: GeneratedRupeeSymbolWhitePNG2Widget(),
              ),
              Positioned(
                left: 268.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 21.0,
                child: GeneratedRupeeSymbolWhitePNG3Widget(),
              ),
              Positioned(
                left: 268.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 21.0,
                child: GeneratedRupeeSymbolWhitePNG4Widget(),
              ),
              Positioned(
                left: 287.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 27.0,
                child: Generated199Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 73.0,
                child: GeneratedGroup80Widget1(),
              ),
              Positioned(
                left: 284.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 27.0,
                child: Generated299Widget(),
              )
            ]),
      ),
    ));
  }
}
