import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedRectangle47Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedELSAWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedDownload43Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedFRIENDSWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedTryusingclothbagsfor2monthsAswellastrymaximumtoreduceth.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedVectorWidget37.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedCHALLENGESWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedGroup77Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/Generated2Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedDownload71Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/Generated1Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedChallengeyourselftousepublictransportationfacilitiesfor.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedGroundtransportation1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedRAHULWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid16widget/generated/GeneratedRectangle54Widget.dart';

/* Frame Android - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 243, 235),
                ),
              ),
              Positioned(
                left: 62.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 43.0,
                child: GeneratedRectangle47Widget1(),
              ),
              Positioned(
                left: 88.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 39.0,
                child: GeneratedCHALLENGESWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 41.0,
                child: GeneratedFRIENDSWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 50.0,
                child: GeneratedRectangle48Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 50.0,
                child: GeneratedRectangle49Widget(),
              ),
              Positioned(
                left: 88.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 45.0,
                child: GeneratedELSAWidget1(),
              ),
              Positioned(
                left: 85.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 29.0,
                child: GeneratedRAHULWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 128.0,
                child: GeneratedRectangle50Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 31.0,
                child: Generated1Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 23.0,
                child: Generated2Widget2(),
              ),
              Positioned(
                left: 62.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 110.0,
                child:
                    GeneratedTryusingclothbagsfor2monthsAswellastrymaximumtoreduceth(),
              ),
              Positioned(
                left: 22.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 115.0,
                child: GeneratedRectangle54Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 100.0,
                child:
                    GeneratedChallengeyourselftousepublictransportationfacilitiesfor(),
              ),
              Positioned(
                left: 14.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 40.0,
                child: GeneratedDownload43Widget2(),
              ),
              Positioned(
                left: 294.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedDownload71Widget(),
              ),
              Positioned(
                left: 284.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 34.0,
                child: GeneratedGroundtransportation1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8833333333333333,
                        translateY: constraints.maxHeight * 0.034375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget37())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 76.0,
                child: GeneratedGroup77Widget(),
              )
            ]),
      ),
    ));
  }
}
