import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedWhatsAppImage20210911at11481Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedDownload21Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedVectorWidget32.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedVectorWidget31.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedVectorWidget30.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedVectorWidget29.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedNEWSWidget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedWhatsAppImage20210911at12111Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedGroup80Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedRectangle8Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedWhatsAppImage20210911at12113Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedWhatsAppImage20210911at12112Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedEXPLOREWidget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedDownload41Widget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedRectangle5Widget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid11widget/generated/GeneratedVIEWMOREWidget2.dart';

/* Frame Android - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 989.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 989.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 232, 243, 235),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.06666666666666667;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          24.0;

                                      double percentHeight =
                                          0.03749996297159378;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          37.08746337890625;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.13333333333333333,
                                            translateY: constraints.maxHeight *
                                                0.8498061809790508,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedVectorWidget29())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 42.0,
                                    top: 397.0,
                                    right: null,
                                    bottom: null,
                                    width: 290.0,
                                    height: 188.0,
                                    child: GeneratedRectangle5Widget4(),
                                  ),
                                  Positioned(
                                    left: 42.0,
                                    top: 153.0,
                                    right: null,
                                    bottom: null,
                                    width: 290.0,
                                    height: 218.0,
                                    child: GeneratedRectangle7Widget2(),
                                  ),
                                  Positioned(
                                    left: 45.0,
                                    top: 625.0,
                                    right: null,
                                    bottom: null,
                                    width: 290.0,
                                    height: 77.0,
                                    child: GeneratedRectangle6Widget2(),
                                  ),
                                  Positioned(
                                    left: 42.0,
                                    top: 743.0,
                                    right: null,
                                    bottom: null,
                                    width: 290.0,
                                    height: 93.0,
                                    child: GeneratedRectangle8Widget3(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 16.0,
                                    right: null,
                                    bottom: null,
                                    width: 34.0,
                                    height: 40.0,
                                    child: GeneratedDownload41Widget4(),
                                  ),
                                  Positioned(
                                    left: 61.0,
                                    top: 63.0,
                                    right: null,
                                    bottom: null,
                                    width: 241.0,
                                    height: 43.0,
                                    child: GeneratedRectangle15Widget(),
                                  ),
                                  Positioned(
                                    left: 89.7978515625,
                                    top: 69.0,
                                    right: null,
                                    bottom: null,
                                    width: 32.351219177246094,
                                    height: 33.55601501464844,
                                    child: GeneratedDownload21Widget1(),
                                  ),
                                  Positioned(
                                    left: 153.0,
                                    top: 69.0,
                                    right: null,
                                    bottom: null,
                                    width: 97.0,
                                    height: 35.0,
                                    child: GeneratedNEWSWidget2(),
                                  ),
                                  Positioned(
                                    left: 41.0,
                                    top: 167.0,
                                    right: null,
                                    bottom: null,
                                    width: 273.0,
                                    height: 190.0,
                                    child:
                                        GeneratedWhatsAppImage20210911at11481Widget(),
                                  ),
                                  Positioned(
                                    left: 50.0,
                                    top: 410.0,
                                    right: null,
                                    bottom: null,
                                    width: 273.0,
                                    height: 162.09375,
                                    child:
                                        GeneratedWhatsAppImage20210911at12111Widget(),
                                  ),
                                  Positioned(
                                    left: 53.0,
                                    top: 636.0,
                                    right: null,
                                    bottom: null,
                                    width: 273.0,
                                    height: 56.91891860961914,
                                    child:
                                        GeneratedWhatsAppImage20210911at12112Widget(),
                                  ),
                                  Positioned(
                                    left: 50.0,
                                    top: 753.0,
                                    right: null,
                                    bottom: null,
                                    width: 273.0,
                                    height: 74.06388854980469,
                                    child:
                                        GeneratedWhatsAppImage20210911at12113Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.06666666666666667;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          24.0;

                                      double percentHeight =
                                          0.023460395897845047;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          23.20233154296875;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.1388888888888889,
                                            translateY: constraints.maxHeight *
                                                0.8868449551511944,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedVectorWidget30())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.06666666666666667;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          24.0;

                                      double percentHeight =
                                          0.023460519325865774;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          23.20245361328125;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.1388888888888889,
                                            translateY: constraints.maxHeight *
                                                0.916170403737993,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedVectorWidget31())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.06944444444444445;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          25.0;

                                      double percentHeight =
                                          0.024224808772967486;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          23.958335876464844;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.8722222222222222,
                                            translateY: constraints.maxHeight *
                                                0.015503875647565111,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedVectorWidget32())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 114.0,
                                    top: 16.0,
                                    right: null,
                                    bottom: null,
                                    width: 137.0,
                                    height: 43.0,
                                    child: GeneratedEXPLOREWidget4(),
                                  ),
                                  Positioned(
                                    left: 151.0,
                                    top: 876.0,
                                    right: null,
                                    bottom: null,
                                    width: 69.0,
                                    height: 17.0,
                                    child: GeneratedVIEWMOREWidget2(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 9.094947017729282e-13,
              top: 572.0,
              right: null,
              bottom: null,
              width: 385.0,
              height: 76.0,
              child: GeneratedGroup80Widget3(),
            )
          ]),
    ));
  }
}
