import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedGroup80Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedDONATEWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedVIEWMOREWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedRectangle28Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedEXPLOREWidget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedRectangle16Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedVectorWidget23.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedGREENPEACEINDIAWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedDONATIONSWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedVectorWidget24.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedRectangle28Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedDownload41Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedDONATEWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedENSYDEWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedLoupe2Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedGreenpeaceusesnonviolentcreativeactiontopavethewaytowar.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedSearchotherNGOSWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedEnvironmentalSynergiesinDevelopmentENSYDEisanorganisati.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid13widget/generated/GeneratedDownload2Widget.dart';

/* Frame Android - 13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 636.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 243, 235),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 147.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 28.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 93.0,
                child:
                    GeneratedGreenpeaceusesnonviolentcreativeactiontopavethewaytowar(),
              ),
              Positioned(
                left: 23.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 158.0,
                child: GeneratedRectangle8Widget2(),
              ),
              Positioned(
                left: 41.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 56.0,
                child:
                    GeneratedEnvironmentalSynergiesinDevelopmentENSYDEisanorganisati(),
              ),
              Positioned(
                left: 47.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 35.0,
                child: GeneratedENSYDEWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 40.0,
                child: GeneratedDownload41Widget2(),
              ),
              Positioned(
                left: 60.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 43.0,
                child: GeneratedRectangle16Widget3(),
              ),
              Positioned(
                left: 87.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 34.0,
                child: GeneratedDownload2Widget(),
              ),
              Positioned(
                left: 128.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 35.0,
                child: GeneratedDONATIONSWidget1(),
              ),
              Positioned(
                left: 44.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 32.0,
                child: GeneratedGREENPEACEINDIAWidget(),
              ),
              Positioned(
                left: 217.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 25.0,
                child: GeneratedRectangle28Widget2(),
              ),
              Positioned(
                left: 235.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 32.0,
                child: GeneratedDONATEWidget(),
              ),
              Positioned(
                left: 217.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 25.0,
                child: GeneratedRectangle28Widget3(),
              ),
              Positioned(
                left: 237.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 25.0,
                child: GeneratedDONATEWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 31.0,
                child: GeneratedRectangle20Widget1(),
              ),
              Positioned(
                left: 87.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 17.0,
                child: GeneratedSearchotherNGOSWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 21.0,
                child: GeneratedLoupe2Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 17.0,
                child: GeneratedVIEWMOREWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06666666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 24.0;

                  double percentHeight = 0.03773584905660377;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 24.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.13333333333333333,
                        translateY: constraints.maxHeight * 0.8852201257861635,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget23())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.03930817610062893;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8583333333333333,
                        translateY:
                            constraints.maxHeight * 0.029874213836477988,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget24())
                  ]);
                }),
              ),
              Positioned(
                left: 103.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 43.0,
                child: GeneratedEXPLOREWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 73.0,
                child: GeneratedGroup80Widget2(),
              )
            ]),
      ),
    ));
  }
}
