import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedSIGNINWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedGroup84Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedInputTextWidget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedButtonPrimaryWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedCheckboxOptionEmptyWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedInputTextWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedEllipse6Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedCheckboxOptionEmptyWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedInputTextWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid3widget/generated/GeneratedInputTextWidget2.dart';

/* Frame Android - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 381.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 243, 235),
                ),
              ),
              Positioned(
                left: 212.4999542236328,
                top: 225.02548217773438,
                right: null,
                bottom: null,
                width: 196.68687438964844,
                height: 205.8211212158203,
                child: GeneratedEllipse6Widget4(),
              ),
              Positioned(
                left: -63.318939208984375,
                top: -172.824462890625,
                right: null,
                bottom: null,
                width: 360.5577392578125,
                height: 339.653076171875,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 90.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 70.0,
                child: GeneratedSIGNINWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 142.0,
                right: 38.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 224.0,
                right: 38.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 306.0,
                right: 38.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget2(),
              ),
              Positioned(
                left: -18.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 196.0764617919922,
                height: 212.56353759765625,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 386.0,
                right: 38.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget3(),
              ),
              Positioned(
                left: 44.0,
                top: 469.0,
                right: 17.0,
                bottom: null,
                width: null,
                height: 17.0,
                child: GeneratedCheckboxOptionEmptyWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 583.0,
                right: 97.0,
                bottom: null,
                width: null,
                height: 25.0,
                child: GeneratedCheckboxOptionEmptyWidget1(),
              ),
              Positioned(
                left: 78.0,
                top: null,
                right: 78.0,
                bottom: 73.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget(),
              ),
              Positioned(
                left: 256.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 33.0,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.08136482939632546;

                  final double height = constraints.maxHeight * 0.0625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.03418010801780881,
                        y: constraints.maxHeight * 0.021847638487815856,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup84Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
