import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedDownload31Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedEXPLOREWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedDownload11Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedVectorWidget16.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedVOLUNTEERINGWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedSHOPPINGWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedDONATIONSWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedGroup79Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedNEWSWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedDownload41Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedDownload1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid6widget/generated/GeneratedDownload21Widget.dart';

/* Frame Android - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 243, 235),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 136.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 338.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 136.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 194.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 136.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 194.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 136.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 56.0,
                child: GeneratedDownload1Widget(),
              ),
              Positioned(
                left: 274.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 63.0,
                child: GeneratedDownload11Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 50.0,
                child: GeneratedDownload21Widget(),
              ),
              Positioned(
                left: 279.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 50.0,
                child: GeneratedDownload31Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 40.0,
                child: GeneratedDownload41Widget(),
              ),
              Positioned(
                left: 86.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 43.0,
                child: GeneratedEXPLOREWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 35.0,
                child: GeneratedNEWSWidget1(),
              ),
              Positioned(
                left: 205.0,
                top: 224.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 33.0,
                child: GeneratedSHOPPINGWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 38.0,
                child: GeneratedDONATIONSWidget(),
              ),
              Positioned(
                left: 190.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 57.0,
                child: GeneratedVOLUNTEERINGWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.0390625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8722222222222222,
                        translateY: constraints.maxHeight * 0.0296875,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget16())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 73.0,
                child: GeneratedGroup79Widget(),
              )
            ]),
      ),
    ));
  }
}
