import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedRectangle64Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedMissionClothBagDay3Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedEllipse21Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedMissionClothBagDay5Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedDownload42Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedEVENTSWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedDownload510Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedRectangle62Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/Generated3Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/Generated4Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedDatepickerWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedGreenpeaceIndiaSeminarWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedEllipse27Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedRectangle60Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/Generated7Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/Generated5Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedEllipse25Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedRectangle66Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedEllipse22Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedGroup80Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedMissionClothBagDay4Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedRectangle65Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedRectangle63Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedEllipse24Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedMissionClothBagDay2Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedCALENDERWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedEllipse23Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedEllipse26Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedMissionClothBagDay1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/Generated21Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/GeneratedDownload43Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid22widget/generated/Generated6Widget1.dart';

/* Frame Android - 22
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid22Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1106.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 353.0,
                            height: 1106.0,
                            decoration: BoxDecoration(
                              border: Border.all(
                                width: 1.0199095010757446,
                                color: Color.fromARGB(255, 0, 0, 0),
                              ),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 232, 243, 235),
                                    ),
                                  ),
                                  Positioned(
                                    left: 5.853515625,
                                    top: 17.33846092224121,
                                    right: null,
                                    bottom: null,
                                    width: 34.67692184448242,
                                    height: 40.79637908935547,
                                    child: GeneratedDownload42Widget(),
                                  ),
                                  Positioned(
                                    left: 306.9927673339844,
                                    top: 17.33846092224121,
                                    right: null,
                                    bottom: null,
                                    width: 32.63710403442383,
                                    height: 34.67692184448242,
                                    child: GeneratedDownload510Widget1(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.106936403442037;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          37.74855041503906;

                                      double percentHeight =
                                          0.028828819233513225;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          31.884674072265625;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.5895953299978974,
                                            translateY: constraints.maxHeight *
                                                0.26666665379005144,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedEllipse27Widget())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: -27.537565231323242,
                                    top: 81.59275817871094,
                                    right: null,
                                    bottom: null,
                                    width: 407.96380615234375,
                                    height: 386.54571533203125,
                                    child: GeneratedDatepickerWidget(),
                                  ),
                                  Positioned(
                                    left: 89.75202941894531,
                                    top: 20.398189544677734,
                                    right: null,
                                    bottom: null,
                                    width: 162.06607055664062,
                                    height: 43.756561279296875,
                                    child: GeneratedCALENDERWidget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width = constraints.maxWidth;

                                      final double height =
                                          constraints.maxHeight *
                                              0.04324327023939026;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.005780324719782929,
                                            y: constraints.maxHeight *
                                                0.40450451042078717,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedRectangle60Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.6675153953833215;

                                      final double height =
                                          constraints.maxHeight *
                                              0.029736206716913426;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.19653175505295015,
                                            y: constraints.maxHeight *
                                                0.4117117359237257,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedMissionClothBagDay1Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width = constraints.maxWidth;

                                      final double height =
                                          constraints.maxHeight *
                                              0.04324327023939026;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                -0.0028901961302284476,
                                            y: constraints.maxHeight *
                                                0.45675672976060977,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedRectangle62Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width = constraints.maxWidth;

                                      final double height =
                                          constraints.maxHeight *
                                              0.04324324264664331;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                -0.0028901961302284476,
                                            y: constraints.maxHeight *
                                                0.5090089766931792,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedRectangle63Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.6790761974648105;

                                      final double height =
                                          constraints.maxHeight *
                                              0.02973628949515427;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.19653175505295015,
                                            y: constraints.maxHeight *
                                                0.460360342512079,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedMissionClothBagDay2Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.6790761110127479;

                                      final double height =
                                          constraints.maxHeight *
                                              0.029736261902407322;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.19942193396030675,
                                            y: constraints.maxHeight *
                                                0.5162162021961177,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedMissionClothBagDay3Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width = constraints.maxWidth;

                                      final double height =
                                          constraints.maxHeight *
                                              0.04324324264664331;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.005780324719782929,
                                            y: constraints.maxHeight *
                                                0.5612611960330018,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedRectangle64Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.6819663763721672;

                                      final double height =
                                          constraints.maxHeight *
                                              0.02703355233880538;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.19942193396030675,
                                            y: constraints.maxHeight *
                                                0.5648648087844711,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedMissionClothBagDay4Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width = constraints.maxWidth;

                                      final double height =
                                          constraints.maxHeight *
                                              0.043243297832137206;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.005780324719782929,
                                            y: constraints.maxHeight *
                                                0.6135135257438121,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedRectangle65Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.6790761110127479;

                                      final double height =
                                          constraints.maxHeight *
                                              0.029736206716913426;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.19942193396030675,
                                            y: constraints.maxHeight *
                                                0.6171171936807753,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedMissionClothBagDay5Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width = constraints.maxWidth;

                                      final double height =
                                          constraints.maxHeight *
                                              0.04324324264664331;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                -0.008670542800730416,
                                            y: constraints.maxHeight *
                                                0.6657657450836347,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedRectangle66Widget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.7282090659857472;

                                      final double height =
                                          constraints.maxHeight *
                                              0.029736372273395116;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.19942193396030675,
                                            y: constraints.maxHeight *
                                                0.674774721776814,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedGreenpeaceIndiaSeminarWidget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.09248554132477757;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          32.647396087646484;

                                      double percentHeight =
                                          0.028828819233513225;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          31.884674072265625;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.037572228537065114,
                                            translateY: constraints.maxHeight *
                                                0.4117117359237257,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedEllipse21Widget())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.04884638799824053;

                                      final double height =
                                          constraints.maxHeight *
                                              0.02524148620274356;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.06647396357809181,
                                            y: constraints.maxHeight *
                                                0.4153152934897011,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: Generated3Widget1(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.09248554132477757;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          32.647396087646484;

                                      double percentHeight =
                                          0.028828791640766276;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          31.8846435546875;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.037572228537065114,
                                            translateY: constraints.maxHeight *
                                                0.4639639828562952,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedEllipse22Widget())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.09248554132477757;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          32.647396087646484;

                                      double percentHeight =
                                          0.02882873645527238;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          31.88458251953125;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.037572228537065114,
                                            translateY: constraints.maxHeight *
                                                0.5162162021961177,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedEllipse23Widget())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.09248554132477757;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          32.647396087646484;

                                      double percentHeight =
                                          0.028828846826260173;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          31.88470458984375;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.037572228537065114,
                                            translateY: constraints.maxHeight *
                                                0.5684684767214342,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedEllipse24Widget())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.09248554132477757;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          32.647396087646484;

                                      double percentHeight =
                                          0.028828791640766276;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          31.8846435546875;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.037572228537065114,
                                            translateY: constraints.maxHeight *
                                                0.6207207512467506,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedEllipse25Widget())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      double percentWidth = 0.09248554132477757;
                                      double scaleX = (constraints.maxWidth *
                                              percentWidth) /
                                          32.647396087646484;

                                      double percentHeight =
                                          0.028828791640766276;
                                      double scaleY = (constraints.maxHeight *
                                              percentHeight) /
                                          31.8846435546875;

                                      return Stack(children: [
                                        TransformHelper.translateAndScale(
                                            translateX: constraints.maxWidth *
                                                0.037572228537065114,
                                            translateY: constraints.maxHeight *
                                                0.6738739841454283,
                                            translateZ: 0,
                                            scaleX: scaleX,
                                            scaleY: scaleY,
                                            scaleZ: 1,
                                            child: GeneratedEllipse26Widget())
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.04306604099003519;

                                      final double height =
                                          constraints.maxHeight *
                                              0.022538804231888563;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.06647396357809181,
                                            y: constraints.maxHeight *
                                                0.4693693467980052,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: Generated4Widget1(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.04884638799824053;

                                      final double height =
                                          constraints.maxHeight *
                                              0.025241513795490507;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.06647396357809181,
                                            y: constraints.maxHeight *
                                                0.522522524511189,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: Generated5Widget1(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.04884638799824053;

                                      final double height =
                                          constraints.maxHeight *
                                              0.025241568980984404;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.06647396357809181,
                                            y: constraints.maxHeight *
                                                0.5738738958486381,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: Generated6Widget1(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.048846398804748364;

                                      final double height =
                                          constraints.maxHeight *
                                              0.025241568980984404;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.06936413167894055,
                                            y: constraints.maxHeight *
                                                0.6243242536272321,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: Generated7Widget1(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.08063828573686205;

                                      final double height =
                                          constraints.maxHeight *
                                              0.025241513795490507;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.052023096057578454,
                                            y: constraints.maxHeight *
                                                0.6783783897137772,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: Generated21Widget1(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 25.497730255126953,
                                    top: 410.0036315917969,
                                    right: null,
                                    bottom: null,
                                    width: 80.47330474853516,
                                    height: 28.457918167114258,
                                    child: GeneratedEVENTSWidget(),
                                  ),
                                  Positioned(
                                    left: 292.7140197753906,
                                    top: 410.0036315917969,
                                    right: null,
                                    bottom: null,
                                    width: 46.915836334228516,
                                    height: 41.816287994384766,
                                    child: GeneratedDownload43Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 572.0,
              right: null,
              bottom: null,
              width: 385.0,
              height: 77.0,
              child: GeneratedGroup80Widget(),
            )
          ]),
    ));
  }
}
