import 'package:flutter/material.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedElsaplantedatreethisweekkeepgoing1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedRectangle16Widget4.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedFF2Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedGroup79Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedEXPLOREWidget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedVectorWidget27.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated8456653Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedRANK3Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated8456656Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated2Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated8456654Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedRAHULWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedVectorWidget26.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedHeyRahulinvitesyouforanewchallengeWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedRectangle5Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated8456657Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated177Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedShare1Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedELSAWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedSARAWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated183Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated3Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated177Widget2.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedSARAWidget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedDownload41Widget3.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated1Widget1.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/GeneratedLEADERBOARDWidget.dart';
import 'package:flutterapp/carbo_20trackapp/generatedandroid18widget/generated/Generated247Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Android - 18
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid18Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 636.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 243, 235),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 50.0,
                child: GeneratedRectangle5Widget3(),
              ),
              Positioned(
                left: 30.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 50.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 50.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 40.0,
                child: GeneratedDownload41Widget3(),
              ),
              Positioned(
                left: 66.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 43.0,
                child: GeneratedRectangle16Widget4(),
              ),
              Positioned(
                left: 99.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 35.0,
                child: GeneratedLEADERBOARDWidget(),
              ),
              Positioned(
                left: 115.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 35.0,
                child: GeneratedSARAWidget(),
              ),
              Positioned(
                left: 115.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 35.0,
                child: GeneratedRAHULWidget(),
              ),
              Positioned(
                left: 113.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 35.0,
                child: GeneratedELSAWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06666666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 24.0;

                  double percentHeight = 0.03773584905660377;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 24.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.13333333333333333,
                        translateY: constraints.maxHeight * 0.8852201257861635,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget26())
                  ]);
                }),
              ),
              Positioned(
                left: 257.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 30.0,
                child: Generated247Widget(),
              ),
              Positioned(
                left: 259.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 30.0,
                child: Generated177Widget1(),
              ),
              Positioned(
                left: 258.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 30.0,
                child: Generated177Widget2(),
              ),
              Positioned(
                left: 260.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 30.0,
                child: Generated183Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 24.0,
                child: Generated1Widget1(),
              ),
              Positioned(
                left: 64.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 24.0,
                child: Generated3Widget2(),
              ),
              Positioned(
                left: 67.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 24.0,
                child: Generated2Widget1(),
              ),
              Positioned(
                left: 220.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 32.0,
                child: Generated8456656Widget(),
              ),
              Positioned(
                left: 223.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 32.0,
                child: Generated8456653Widget1(),
              ),
              Positioned(
                left: 222.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 32.0,
                child: Generated8456654Widget(),
              ),
              Positioned(
                left: 216.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 32.0,
                child: Generated8456657Widget(),
              ),
              Positioned(
                left: 2.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 54.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 82.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 35.0,
                child: GeneratedSARAWidget1(),
              ),
              Positioned(
                left: 290.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 56.0,
                child: GeneratedFF2Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 19.0,
                child: GeneratedRANK3Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 54.0,
                child: GeneratedRectangle38Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 54.0,
                child: GeneratedRectangle39Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 40.0,
                child: GeneratedElsaplantedatreethisweekkeepgoing1Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 40.0,
                child: GeneratedHeyRahulinvitesyouforanewchallengeWidget(),
              ),
              Positioned(
                left: 303.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 40.0,
                child: GeneratedShare1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06944444444444445;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.03930817610062893;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8611111111111112,
                        translateY:
                            constraints.maxHeight * 0.029874213836477988,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget27())
                  ]);
                }),
              ),
              Positioned(
                left: 106.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 43.0,
                child: GeneratedEXPLOREWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 77.0,
                child: GeneratedGroup79Widget2(),
              )
            ]),
      ),
    ));
  }
}
